id: IBCBABC73
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:39:34+00:00'
last_modified: '2022-06-08T09:29:34.406623+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3556
  title: སུམ་རྟགས་རྩ་བ་དང་འགྲེལ་བ་ནོར་བུའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A20:
      image_group_id: I1KG3628
      title: ''
      total_pages: 104
      order: 1
      base_file: 3A20.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
