id: P006903
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:45.271402
source_metadata:
  id: bdr:W1KG3556
  title: སུམ་རྟགས་རྩ་བ་དང་འགྲེལ་བ་ནོར་བུའི་མེ་ལོང
  author: ''
  volumes:
    264803f9e5374e4ba6083cbda30b2b77:
      image_group_id: I1KG3628
      title: ''
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
